### PR TITLE
Fix "edit" button that was mistakenly "add"

### PR DESCRIPTION
**Pull request by ghost**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | When you edit a link the button and the title is ADD instead Update
| Type?         | bug fix 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/22282
| How to test?  | Check wording on update and add 
| Sponsor company   | @Touxten

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Comment by okom3pom** [comment]
Hi @PierreRambaud thank you for review but the QA can't test this because the tpl is override here : https://github.com/PrestaShop/PrestaShop/pull/24335

I update the module for theme makers, i can add how to test : Remove the .tpl from your theme ?

**Comment by okom3pom** [comment]
I upadate how to test

**Review by NeOMakinG — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

Please check the Conflicting files.

Thank you!

**Comment by okom3pom** [comment]
Hello @khouloudbelguith 

I have not forgotten you but when I resolve the conflict it produces an error :) 

I have opened a issue and made a PR

**Comment by PierreRambaud** [comment]
> Hello @khouloudbelguith
> 
> I have not forgotten you but when I resolve the conflict it produces an error :)
> 
> I have opened a issue and made a PR

Could you tell us more about your error when trying to resolve conflict?

**Comment by okom3pom** [comment]
Hi @PierreRambaud I opened an issue https://github.com/PrestaShop/PrestaShop/issues/25142  the last PR merge made an error 500.

I made a PR when it will be merged I could solve the conflict problem

**Comment by atomiix** [comment]
@okom3pom I rebased your PR ;)

**Comment by okom3pom** [comment]
Thank you @atomiix

**Review by PierreRambaud — DISMISSED** [review]

**Comment by sarahdib** [comment]
Hello @okom3pom 

Thanks for your contribution.

There is an issue after editing the link see the screenrecord : 
https://drive.google.com/file/d/1MPeYfcn4RLNQPeP6WRd5TASSNW0oWMa-/view

Could you check and correct this behavior ? Thank you :)

**Comment by atomiix** [comment]
Thanks @okom3pom

**Pull request merged**
